---
- name: Configure host
  hosts: host01
  become: true
  tasks:
    - name: Create user cloudru
      user:
        name: cloudru
        password: "{{ 'cloudpass' | password_hash('sha512', 'mysalt') }}"
        state: present

    - name: Allow ssh login with key
      authorized_key:
        user: cloudru
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

    - name: Disable root ssh login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes
      notify:
        - restart sshd

    - name: Copy public key for cloudru
      shell: "cp /root/.ssh/id_rsa.pub /home/cloudru/.ssh/authorized_keys"
      args:
        creates: /home/cloudru/.ssh/authorized_keys

  handlers:
    - name: restart sshd
      # Enter the appropriate command to restart the SSH service on your host.
      # For example, "/etc/init.d/sshd restart" or "systemctl restart sshd".
      command: /etc/init.d/sshd restart
