# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          env:
            - name: AUTHOR
              value: {{ .Values.author }}
          ports:
            - containerPort: 80
