apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  namespace: my-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: islam/my_app
          image: islam/my_app
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-ns
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
